### ISSUE TITLE
AY-6907 Default value for Node Exposed Knobs

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-nuke#28]
## Problem

You can create new knobs exposed on write node, but you cannot set their default value.

![image](https://github.com/user-attachments/assets/f0ab618e-1446-4770-a2fb-ff48d3376a83)

But you can do it on **Preceding Nodes** knobs.

![image](https://github.com/user-attachments/assets/c05a263f-97db-4c6e-88eb-c786422e4a0b)

It would be helpful be able to set default value there too.

**ClickUp [AY-6907](https://app.clickup.com/t/6658547/AY-6907)**

**Comment by jakubjezek001** [comment]
Let's admit that this isn't very clear and definitely needs to be redesigned. However, you can set the default settings for a Write node knob using the following path: `ayon+settings://nuke/imageio/nodes/required_nodes/0/knobs`. As you can see, this is done through ImageIO rather than the Create node's defaults.

**Comment by antirotor** [comment]
So it seems it is fine, closing this issue. Feel free to reopen.
